### ISSUE TITLE
Please update instructions

### ISSUE THREAD

**Issue by codewithbjim** [NathanaelA/nativescript-localstorage#19]
The instructions at https://www.npmjs.com/package/nativescript-localstorage is missing the newly added
setItemObject();

Took me a long time to debug things up. Didn't knew objects have a different handling now.

**Comment by NathanaelA** [comment]
I just looked at the the npm url and this is in the docs:
![image](https://user-images.githubusercontent.com/850871/46647039-5430ab80-cb53-11e8-91c8-8976c43bf4e2.png)

I also double checked https://plugins.nativescript.rocks, and it has the correct documentation also.

I also updated the main directories repo's readme to point to the main readme.
