### ISSUE TITLE
Is localstorage still saved after app update?

### ISSUE THREAD

**Issue by NL33** [NathanaelA/nativescript-localstorage#20]
I am using local storage on an app (the plugin is great--thank you). If I have items saved with localStorage, and then I run a new bundle (eg., running '$ tns run ios --bundle --env.development --env.uglify --env.aot' to test again on a device after it had been unplugged), it deletes the items saved in localStorage.  

This is fine for development / testing purposes.

However, it would be a concern if the app is released to the app store, and then any subsequent app update means that the items saved with localStorage on a user's phone get deleted. 

I haven't been able to nail down this issue yet.

Do localStorage items on an app store app survive an app update?

**Comment by NathanaelA** [comment]
Yes, app upgrades will persist the data.  Using TNS frequently de-installs then installs the new version; the manual de-install is what deletes the data.

**Comment by NL33** [comment]
Great to hear. Thanks. And thanks for the plugin--very easy to use.
