### ISSUE TITLE
Can't install plugin

### ISSUE THREAD

**Issue by Natym-git** [NathanaelA/nativescript-localstorage#30]
Hi Nathanael! I am trying to install the plugin, but when I run **npm install @proplugins/nativescript-localstorage --save**  or **tns plugin add @proplugins/nativescript-localstorage** I get this error 

npm ERR! code E404
npm ERR! 404 Not Found: @proplugins/nativescript-localstorage@latest

What can be wrong?
thanks!

**Comment by NathanaelA** [comment]
Well the @proplugins version you have to have logged into the ProPlugins NPM server; see https://proplugins.org

**Comment by jpolstre** [comment]
Hey, tell us the price at the entrance of your page, so we don't waste time.
