### ISSUE TITLE
404 Not Found: @proplugins/nativescript-localstorage@latest

### ISSUE THREAD

**Issue by map7** [NathanaelA/nativescript-localstorage#31]
When trying to install nativescript-localstorage in my nativescript app I get the following error

```
% tns plugin add @proplugins/nativescript-localstorage      
npm WARN @angular/http@8.0.0-beta.10 requires a peer of @angular/core@8.0.0-beta.10+1.sha-a28b3e3 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/http@8.0.0-beta.10 requires a peer of @angular/platform-browser@8.0.0-beta.10+1.sha-a28b3e3 but none is installed. You must install peer dependencies yourself.
npm WARN angular-token@7.0.1 requires a peer of @angular/common@^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular-token@7.0.1 requires a peer of @angular/core@^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ @proplugins/nativescript-localstorage@2.2.1
updated 1 package and audited 11726 packages in 5.54s
found 0 vulnerabilities

404 Not Found: @proplugins/nativescript-localstorage@latest
# tns plugin add

### Description

Installs the specified plugin and any packages that it depends on.

### Commands

┌─────────┬───────────────────────────────┐
│ Usage   │ Synopsis                      │
│ General │ $ tns plugin add <Plugin>     │
│ Alias   │ $ tns plugin install <Plugin> │
└─────────┴───────────────────────────────┘

### Arguments

    * <Plugin> is a valid NativeScript plugin, specified by any of the following.
        * A <Name> or <Name>@<Version> where <Name> is the name of a plugin that is published in the npm registry and <Version> is a valid version of this plugin.
          * A <Local Path> to the directory which contains the plugin, including its package.json file.
          * A <Local Path> to a .tar.gz archive containing a directory with the plugin and its package.json file.
          * A <URL> which resolves to a .tar.gz archive containing a directory with the plugin and its package.json file.
          * A <git Remote URL> which resolves to a .tar.gz archive containing a directory with the plugin and its package.json file.
```

I can install the @proplugins/nativescript-localstorage through npm though, but not through the tns plugin.

**Comment by NathanaelA** [comment]
This was a known issue -- The NativeScript command line was using older NPM components so it didn't understand how to communicate with other npm servers.    TNS 6.1 should have fixed this issue.   

If you are using anything prior to TNS 6.1 you can do `npm i @proplugins/nativescript-localstorage --save`

**Comment by BearOutThere** [comment]
Seeing the same issue on Ns 6.1.2  for both npm install and tns plugin add.

**Comment by NathanaelA** [comment]
@bearoutthere -  I assume you are also trying to install the `@proplugins` version --- if so, you need to make sure you have followed the setting up npm in the [https://accounts.nativescript.rocks/subscription/current](https://accounts.nativescript.rocks/subscription/current) page

**Comment by BearOutThere** [comment]
I missed that part.  Thanks Nathanael.  Just signed up for a two license subscription.  
Got another question.  Will post it as a separate issue.

**Comment by Jord-X** [comment]
@NathanaelA Just a heads up, that link isn't working anymore.

**Comment by NathanaelA** [comment]
@Jord-X - The link works fine, you just have to have you be signed in.    If you aren't signed in, then this account: https://accounts.nativescript.rocks/subscribe

**Comment by odedBartov** [comment]
> @bearoutthere - I assume you are also trying to install the `@proplugins` version --- if so, you need to make sure you have followed the setting up npm in the https://accounts.nativescript.rocks/subscription/current page

I have the same roblem and i am not sure what i am suppose to do. Is this NS package requires payment?

**Comment by NathanaelA** [comment]
@odedBartov - Yes, ProPlugins is a subscription service, we use the subscriptions to keep all the plugins updated and working and fix any issues people find.
