### ISSUE TITLE
nativescript local storage issue

### ISSUE THREAD

**Issue by EddyMurphy95** [NathanaelA/nativescript-localstorage#34]
hello, I am trying to use local storage in nativescript and this is what i am getting.
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'getItem' of undefined

**Comment by NathanaelA** [comment]
About a year ago, I moved a large chunk of my plugins to ProPlugins.  https://www.proplugins.org -- so the github version of the plugin is not being maintained anymore...   

If you are using NativeScript 6+, then it is very likely this is the cause of your issue as many plugins broke in NS6...    The current ProPlugins version of all my plugins all support NS6 properly, and are maintained...  :grinning:

**Comment by EddyMurphy95** [comment]
Okay..so do you have a plugin for an epub reader that can decrypt files
from a DRM.

**Comment by NathanaelA** [comment]
You can check https://npm.proplugins.org/ to see what plugins are available...

**Comment by EddyMurphy95** [comment]
Okay ...just checked it seems you don't have a plugin for an epub reader
