### ISSUE TITLE
WebPack "global" usage

### ISSUE THREAD

**Issue by NathanaelA** [NathanaelA/nativescript-localstorage#4]
I have a report that the global.localstorage maybe not be available in a webpacked version.   This needs to be confirmed...  
Need  a sample app for WebPack/Angular with just localstorage showing Global doesn't work but local require does work...

**Comment by DanielKucal** [comment]
It works well in my project based on [sample-Groceries](https://github.com/NativeScript/sample-Groceries) just after adding `require('nativescript-localstorage');` to `app/vendor.ts` file.

**Comment by NathanaelA** [comment]
@DanielKucal  - Thanks.
