### ISSUE TITLE
Q: Why use file read/write methods?

### ISSUE THREAD

**Issue by pitAlex** [NathanaelA/nativescript-localstorage#6]
I see the plugin using file to store values. Is it faster then accessing native apis and using android SharedPreferences or ios NSUserDefaults?

**Comment by NathanaelA** [comment]
A couple reasons.
1. SharedPrefs/nsuserdefaults goto a db; this is more overhead especially for larger values.
2. I'm using a method to keep all the saves as close to each other as possible eliminating extra disk writes. 
3. If you want sharedPref/nsUserDefaults then use AppSettings.
